version: "3.8"
name: abernathyclinic
services:

  # MySQL service database
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=abernathyclinic
    ports:
      - 3306:3306

  # MongoDB service database    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=abernathyclinic
    ports:
      - 27017:27017    

  # Patients micro-service
  abernathy-patients:
    image: etiennev/abernathy-patients:latest
    container_name: microservice-patients
    depends_on:
      - mysql
    command: bash -c "sleep 10; start.sh" # Waiting for MySQL to start
    ports:
      - 9001:9001
    environment:
      SPRING_APPLICATION_JSON: '{
        "notes.url" : "abernathy-notes:9002",
        "spring.datasource.url" : "jdbc:mysql://mysql:3306/abernathyclinic?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root"
      }'   

  # Notes micro-service 
  abernathy-notes:
    image: etiennev/abernathy-notes:latest
    container_name: microservice-notes
    depends_on:
      - mongodb
    command: bash -c "sleep 10; start.sh" # Waiting for MongoDB to start
    ports:
      - 9002:9002
    environment:
       SPRING_APPLICATION_JSON: '{
        "patients.url" : "abernathy-patients:9001",
        "spring.data.mongodb.host" : "mongodb",
        "spring.data.mongodb.port" : "27017",
        "spring.data.mongodb.database" : "abernathyclinic"
      }'

  # Reports micro-service
  abernathy-reports:
    image: etiennev/abernathy-reports:latest
    container_name: microservice-reports
    ports:
      - 9003:9003
    environment:
       SPRING_APPLICATION_JSON: '{
        "patients.url" : "abernathy-patients:9001",
        "notes.url" : "abernathy-notes:9002"
      }'
  
  # Web Interface
  abernathy-webinterface:
    image: etiennev/abernathy-webinterface:latest
    container_name: microservice-webinterface
    ports:
      - 8080:8080
    environment:
       SPRING_APPLICATION_JSON: '{
        "patients.url" : "abernathy-patients:9001",
        "notes.url" : "abernathy-notes:9002",
        "reports.url" : "abernathy-reports:9003"
      }'
        
